package NetflixAppGUI;


import Credentials.Language;
import Show.Genres;
import Show.Quality;
import Show.Show;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import Show.ShowCollection;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author MSI
 */

public class CRUDNetflixPanel extends javax.swing.JPanel {

    DefaultListModel<Show> model;
    /**
     * Creates new form AddShowsPanel
     */
    public CRUDNetflixPanel() {
        model = new DefaultListModel<>();
        initComponents();
        showsList.setModel(model);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        titleTxt = new javax.swing.JTextField();
        releaseDateTxt = new javax.swing.JTextField();
        genreCombo = new javax.swing.JComboBox<>();
        langCombo = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AverageRatingTxt = new javax.swing.JLabel();
        actorsTxt = new javax.swing.JTextField();
        numOfViewsTxt = new javax.swing.JTextField();
        synopsisTxt = new javax.swing.JTextField();
        averageRatingTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        showsList = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        qualityCombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        jLabel1.setText("Enter show information:");

        jLabel2.setText("Ttile: ");

        jLabel3.setText("Release Date:");

        jLabel4.setText("Quality:");

        jLabel5.setText("Genre:");

        jLabel6.setText("Language:");

        titleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTxtActionPerformed(evt);
            }
        });

        releaseDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                releaseDateTxtActionPerformed(evt);
            }
        });

        genreCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Genres.values())
        );
        genreCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreComboActionPerformed(evt);
            }
        });

        langCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Language.values()));
        langCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                langComboActionPerformed(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(51, 0, 255));
        addBtn.setText("Add Show");
        addBtn.setActionCommand("<none>");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editBtn.setForeground(new java.awt.Color(51, 0, 255));
        editBtn.setText("Edit Show");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(51, 0, 255));
        deleteBtn.setText("Delete Show");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Actors:");

        jLabel8.setText("Number of Views:");

        AverageRatingTxt.setText("Average Rating:");

        actorsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actorsTxtActionPerformed(evt);
            }
        });

        numOfViewsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOfViewsTxtActionPerformed(evt);
            }
        });

        synopsisTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                synopsisTxtActionPerformed(evt);
            }
        });

        averageRatingTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                averageRatingTxtActionPerformed(evt);
            }
        });

        showsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        showsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                showsListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(showsList);

        jLabel10.setText("Shows:");

        qualityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Quality.values()));

        jLabel11.setText("Synopsis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(AverageRatingTxt)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(genreCombo, 0, 125, Short.MAX_VALUE)
                                .addComponent(actorsTxt)
                                .addComponent(numOfViewsTxt)
                                .addComponent(averageRatingTxt)
                                .addComponent(synopsisTxt)
                                .addComponent(langCombo, 0, 125, Short.MAX_VALUE)
                                .addComponent(qualityCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(releaseDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(addBtn)
                                .addGap(43, 43, 43)
                                .addComponent(editBtn)
                                .addGap(42, 42, 42)
                                .addComponent(deleteBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(releaseDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(qualityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(genreCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(langCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(actorsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(numOfViewsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AverageRatingTxt)
                            .addComponent(averageRatingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(synopsisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(editBtn)
                    .addComponent(deleteBtn))
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void titleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTxtActionPerformed

    private void releaseDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_releaseDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_releaseDateTxtActionPerformed

    private void langComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_langComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_langComboActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String title = titleTxt.getText();
        if(title.isEmpty()){
            
            
        JOptionPane.showMessageDialog(CRUDNetflixPanel.this,""+"Please provide a valid title.","Adding Shows",JOptionPane.ERROR_MESSAGE);
        return;}
        
        String releaseDate = releaseDateTxt.getText();
        //Exception for release date
        
        Quality quality = (Quality)qualityCombo.getSelectedItem();
        Genres genre = (Genres)genreCombo.getSelectedItem();
        Language language = (Language)langCombo.getSelectedItem();
        String names = actorsTxt.getText();
        String numOfViewsStr = numOfViewsTxt.getText();
        int numOfViews = 0;
        
        try{
            numOfViews = Integer.parseInt(numOfViewsStr);
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(CRUDNetflixPanel.this,"Please provide a valid number.","Adding Shows",JOptionPane.ERROR_MESSAGE);
        }
        
        String averageRatingStr = averageRatingTxt.getText();
        double averageRating = 0.0;
        try{
        averageRating = Double.parseDouble(averageRatingStr);
        }catch(NumberFormatException ex1){
            JOptionPane.showMessageDialog(CRUDNetflixPanel.this,"Please provide a valid number.","Adding Shows",JOptionPane.ERROR_MESSAGE);
        }
        String synopsis = synopsisTxt.getText();
        Show SH = new Show(title,releaseDate,quality,genre,language,names,numOfViews,averageRating,synopsis);
        //
        ShowCollection.addShow(SH);
        model.addElement(SH);
        
        
        titleTxt.setText("");
        releaseDateTxt.setText("");
        actorsTxt.setText("");
        numOfViewsTxt.setText("");
        averageRatingTxt.setText("");
        synopsisTxt.setText("");

        showsList.setSelectedValue(null, true);
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        Show toDel = showsList.getSelectedValue();
        
        ShowCollection.removeShow(toDel);
        model.removeElement(toDel);
        showsList.setSelectedValue(null, true);
        
        titleTxt.setText("");
        releaseDateTxt.setText("");
        actorsTxt.setText("");
        numOfViewsTxt.setText("");
        averageRatingTxt.setText("");
        synopsisTxt.setText("");
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void actorsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actorsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actorsTxtActionPerformed

    private void numOfViewsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOfViewsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numOfViewsTxtActionPerformed

    private void averageRatingTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_averageRatingTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_averageRatingTxtActionPerformed

    private void synopsisTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_synopsisTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_synopsisTxtActionPerformed

    private void showsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_showsListValueChanged
        if(evt.getValueIsAdjusting()) return;
        Show SH = showsList.getSelectedValue();
        
        if(SH == null) return;
        
        titleTxt.setText(SH.getTitle());
        releaseDateTxt.setText(SH.getReleaseDate());
        qualityCombo.setSelectedItem(SH.getQuality().name());
        genreCombo.setSelectedItem(SH.getGenres().name());
        langCombo.setSelectedItem(SH.getLanguage().name());
        actorsTxt.setText(SH.getNames());
        numOfViewsTxt.setText(String.valueOf(SH.getNumOfViews()));
        averageRatingTxt.setText(String.valueOf(SH.getAverageRating()));
        synopsisTxt.setText(SH.getSynopsis());

    }//GEN-LAST:event_showsListValueChanged

    private void genreComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreComboActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        
        Show newShow = showsList.getSelectedValue();
        String title = titleTxt.getText();
        if(title.isEmpty()){
            
            
        JOptionPane.showMessageDialog(CRUDNetflixPanel.this,""+"Please provide a valid title.","Adding Shows",JOptionPane.ERROR_MESSAGE);
        return;}
        
        String releaseDate = releaseDateTxt.getText();
        //Exception for release date
        
        Quality quality = (Quality)qualityCombo.getSelectedItem();
        Genres genre = (Genres)genreCombo.getSelectedItem();
        Language language = (Language)langCombo.getSelectedItem();
        String names = actorsTxt.getText();
        String numOfViewsStr = numOfViewsTxt.getText();
        int numOfViews = 0;
        
        try{
            numOfViews = Integer.parseInt(numOfViewsStr);
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(CRUDNetflixPanel.this,"Please provide a valid number.","Adding Shows",JOptionPane.ERROR_MESSAGE);
        }
        
        String averageRatingStr = averageRatingTxt.getText();
        double averageRating = 0.0;
        try{
        averageRating = Double.parseDouble(averageRatingStr);
        }catch(NumberFormatException ex1){
            JOptionPane.showMessageDialog(CRUDNetflixPanel.this,"Please provide a valid number.","Adding Shows",JOptionPane.ERROR_MESSAGE);
        }
        String synopsis = synopsisTxt.getText();
        Show nSH = new Show(title,releaseDate,quality,genre,language,names,numOfViews,averageRating,synopsis);
        
        ShowCollection.editShow(newShow, nSH);
        model.removeElement(newShow);
        model.addElement(nSH);
        
        titleTxt.setText("");
        releaseDateTxt.setText("");
        actorsTxt.setText("");
        numOfViewsTxt.setText("");
        averageRatingTxt.setText("");
        synopsisTxt.setText("");
        showsList.setSelectedValue(null, true);
        
    }//GEN-LAST:event_editBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AverageRatingTxt;
    private javax.swing.JTextField actorsTxt;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField averageRatingTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JComboBox<Genres> genreCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<Language> langCombo;
    private javax.swing.JTextField numOfViewsTxt;
    private javax.swing.JComboBox<Quality> qualityCombo;
    private javax.swing.JTextField releaseDateTxt;
    static javax.swing.JList<Show> showsList;
    private javax.swing.JTextField synopsisTxt;
    private javax.swing.JTextField titleTxt;
    // End of variables declaration//GEN-END:variables
}
